// Minimal ABI slice — just what the MC agent and web app need to read/write.
// Regenerated by hand to avoid depending on Hardhat's build artifacts at runtime
// (artifacts/ isn't guaranteed to exist wherever this script runs from).
module.exports = [
  "event SessionOpened(uint256 indexed sessionId, address indexed host, string code, string title, uint256 minSpray, uint64 timestamp)",
  "event Joined(uint256 indexed sessionId, address indexed guest, string name, uint64 timestamp)",
  "event Sprayed(uint256 indexed sessionId, address indexed guest, uint256 amount, uint256 guestTotal, uint256 sessionTotal, uint64 sprayIndex, uint64 timestamp)",
  "event Gifted(uint256 indexed sessionId, address indexed guest, uint256 amount, uint64 timestamp)",
  "event Hyped(uint256 indexed sessionId, address indexed agent, string line, uint64 timestamp)",
  "event SessionClosed(uint256 indexed sessionId, uint256 total, uint64 timestamp)",
  "event Settled(uint256 indexed sessionId, address indexed recipient, uint256 amount)",

  "function openSession(string sessionCode, string sessionTitle, uint256 minimumSpray, tuple(address recipient, uint16 bps)[] splits) returns (uint256)",
  "function join(uint256 sessionId, string name)",
  "function spray(uint256 sessionId) payable",
  "function gift(uint256 sessionId) payable",
  "function hype(uint256 sessionId, string line)",
  "function closeSession(uint256 sessionId)",
  "function settle(uint256 sessionId, address recipient)",
  "function settleAll(uint256 sessionId)",
  "function sessionByCode(string sessionCode) view returns (uint256)",
  "function getSession(uint256 sessionId) view returns (tuple(address host, uint64 createdAt, bool open, uint128 total, uint64 sprayCount, uint64 giftCount))",
  "function getSplits(uint256 sessionId) view returns (tuple(address recipient, uint16 bps)[])",
  "function guestName(uint256, address) view returns (string)",
  "function sprayedBy(uint256, address) view returns (uint256)",
];
